# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/GitHub/Asio/Asio/Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/GitHub/Asio/Asio/Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/GitHub/Asio/Asio/Server/CMakeFiles /mnt/d/GitHub/Asio/Asio/Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/GitHub/Asio/Asio/Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameserver

# Build rule for target.
gameserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameserver
.PHONY : gameserver

# fast build rule for target.
gameserver/fast:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/build
.PHONY : gameserver/fast

# target to build an object file
AsioAcceptor.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioAcceptor.o
.PHONY : AsioAcceptor.o

# target to preprocess a source file
AsioAcceptor.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioAcceptor.i
.PHONY : AsioAcceptor.i

# target to generate assembly for a file
AsioAcceptor.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioAcceptor.s
.PHONY : AsioAcceptor.s

# target to build an object file
AsioSocket.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioSocket.o
.PHONY : AsioSocket.o

# target to preprocess a source file
AsioSocket.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioSocket.i
.PHONY : AsioSocket.i

# target to generate assembly for a file
AsioSocket.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/AsioSocket.s
.PHONY : AsioSocket.s

# target to build an object file
Logger.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Logger.o
.PHONY : Logger.o

# target to preprocess a source file
Logger.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Logger.i
.PHONY : Logger.i

# target to generate assembly for a file
Logger.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Logger.s
.PHONY : Logger.s

# target to build an object file
LogicSystem.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/LogicSystem.o
.PHONY : LogicSystem.o

# target to preprocess a source file
LogicSystem.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/LogicSystem.i
.PHONY : LogicSystem.i

# target to generate assembly for a file
LogicSystem.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/LogicSystem.s
.PHONY : LogicSystem.s

# target to build an object file
Main.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Main.o
.PHONY : Main.o

# target to preprocess a source file
Main.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Main.i
.PHONY : Main.i

# target to generate assembly for a file
Main.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/Main.s
.PHONY : Main.s

# target to build an object file
ManagerModule.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModule.o
.PHONY : ManagerModule.o

# target to preprocess a source file
ManagerModule.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModule.i
.PHONY : ManagerModule.i

# target to generate assembly for a file
ManagerModule.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModule.s
.PHONY : ManagerModule.s

# target to build an object file
ManagerModuleBase.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleBase.o
.PHONY : ManagerModuleBase.o

# target to preprocess a source file
ManagerModuleBase.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleBase.i
.PHONY : ManagerModuleBase.i

# target to generate assembly for a file
ManagerModuleBase.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleBase.s
.PHONY : ManagerModuleBase.s

# target to build an object file
ManagerModuleManager.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleManager.o
.PHONY : ManagerModuleManager.o

# target to preprocess a source file
ManagerModuleManager.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleManager.i
.PHONY : ManagerModuleManager.i

# target to generate assembly for a file
ManagerModuleManager.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/ManagerModuleManager.s
.PHONY : ManagerModuleManager.s

# target to build an object file
MessageCirularQueue.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageCirularQueue.o
.PHONY : MessageCirularQueue.o

# target to preprocess a source file
MessageCirularQueue.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageCirularQueue.i
.PHONY : MessageCirularQueue.i

# target to generate assembly for a file
MessageCirularQueue.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageCirularQueue.s
.PHONY : MessageCirularQueue.s

# target to build an object file
MessageProcessor.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageProcessor.o
.PHONY : MessageProcessor.o

# target to preprocess a source file
MessageProcessor.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageProcessor.i
.PHONY : MessageProcessor.i

# target to generate assembly for a file
MessageProcessor.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MessageProcessor.s
.PHONY : MessageProcessor.s

# target to build an object file
MsgInstanceMgr.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MsgInstanceMgr.o
.PHONY : MsgInstanceMgr.o

# target to preprocess a source file
MsgInstanceMgr.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MsgInstanceMgr.i
.PHONY : MsgInstanceMgr.i

# target to generate assembly for a file
MsgInstanceMgr.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/MsgInstanceMgr.s
.PHONY : MsgInstanceMgr.s

# target to build an object file
NetProxy.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/NetProxy.o
.PHONY : NetProxy.o

# target to preprocess a source file
NetProxy.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/NetProxy.i
.PHONY : NetProxy.i

# target to generate assembly for a file
NetProxy.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/NetProxy.s
.PHONY : NetProxy.s

# target to build an object file
PerfStatistics.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/PerfStatistics.o
.PHONY : PerfStatistics.o

# target to preprocess a source file
PerfStatistics.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/PerfStatistics.i
.PHONY : PerfStatistics.i

# target to generate assembly for a file
PerfStatistics.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/PerfStatistics.s
.PHONY : PerfStatistics.s

# target to build an object file
StringHelper.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/StringHelper.o
.PHONY : StringHelper.o

# target to preprocess a source file
StringHelper.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/StringHelper.i
.PHONY : StringHelper.i

# target to generate assembly for a file
StringHelper.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/StringHelper.s
.PHONY : StringHelper.s

# target to build an object file
SystemConfig.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/SystemConfig.o
.PHONY : SystemConfig.o

# target to preprocess a source file
SystemConfig.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/SystemConfig.i
.PHONY : SystemConfig.i

# target to generate assembly for a file
SystemConfig.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/SystemConfig.s
.PHONY : SystemConfig.s

# target to build an object file
TimeHelper.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimeHelper.o
.PHONY : TimeHelper.o

# target to preprocess a source file
TimeHelper.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimeHelper.i
.PHONY : TimeHelper.i

# target to generate assembly for a file
TimeHelper.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimeHelper.s
.PHONY : TimeHelper.s

# target to build an object file
TimerManager.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimerManager.o
.PHONY : TimerManager.o

# target to preprocess a source file
TimerManager.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimerManager.i
.PHONY : TimerManager.i

# target to generate assembly for a file
TimerManager.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/TimerManager.s
.PHONY : TimerManager.s

# target to build an object file
UserModule.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModule.o
.PHONY : UserModule.o

# target to preprocess a source file
UserModule.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModule.i
.PHONY : UserModule.i

# target to generate assembly for a file
UserModule.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModule.s
.PHONY : UserModule.s

# target to build an object file
UserModuleBase.o:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModuleBase.o
.PHONY : UserModuleBase.o

# target to preprocess a source file
UserModuleBase.i:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModuleBase.i
.PHONY : UserModuleBase.i

# target to generate assembly for a file
UserModuleBase.s:
	$(MAKE) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/UserModuleBase.s
.PHONY : UserModuleBase.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gameserver"
	@echo "... edit_cache"
	@echo "... AsioAcceptor.o"
	@echo "... AsioAcceptor.i"
	@echo "... AsioAcceptor.s"
	@echo "... AsioSocket.o"
	@echo "... AsioSocket.i"
	@echo "... AsioSocket.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... LogicSystem.o"
	@echo "... LogicSystem.i"
	@echo "... LogicSystem.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... ManagerModule.o"
	@echo "... ManagerModule.i"
	@echo "... ManagerModule.s"
	@echo "... ManagerModuleBase.o"
	@echo "... ManagerModuleBase.i"
	@echo "... ManagerModuleBase.s"
	@echo "... ManagerModuleManager.o"
	@echo "... ManagerModuleManager.i"
	@echo "... ManagerModuleManager.s"
	@echo "... MessageCirularQueue.o"
	@echo "... MessageCirularQueue.i"
	@echo "... MessageCirularQueue.s"
	@echo "... MessageProcessor.o"
	@echo "... MessageProcessor.i"
	@echo "... MessageProcessor.s"
	@echo "... MsgInstanceMgr.o"
	@echo "... MsgInstanceMgr.i"
	@echo "... MsgInstanceMgr.s"
	@echo "... NetProxy.o"
	@echo "... NetProxy.i"
	@echo "... NetProxy.s"
	@echo "... PerfStatistics.o"
	@echo "... PerfStatistics.i"
	@echo "... PerfStatistics.s"
	@echo "... StringHelper.o"
	@echo "... StringHelper.i"
	@echo "... StringHelper.s"
	@echo "... SystemConfig.o"
	@echo "... SystemConfig.i"
	@echo "... SystemConfig.s"
	@echo "... TimeHelper.o"
	@echo "... TimeHelper.i"
	@echo "... TimeHelper.s"
	@echo "... TimerManager.o"
	@echo "... TimerManager.i"
	@echo "... TimerManager.s"
	@echo "... UserModule.o"
	@echo "... UserModule.i"
	@echo "... UserModule.s"
	@echo "... UserModuleBase.o"
	@echo "... UserModuleBase.i"
	@echo "... UserModuleBase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

